#The config file :
#This is just a config file, not a lang file.
#To have the text, go in the lang.yml, thanks.

#The Dungeon Worlguard Zone
WorldguardZone: 'dungeons'

#Put 'name' if you want to detect the npc with his name. 
#Put 'id' if you want to detect the npc with his id.
#Put 'all' if you want to detect the npc with his id and name.
HowVerify: 'id'

#The name of the NPC
NPCName: 'Messis'

#The Id of the NPC
NPCId: 2

#Material informations
material: WHEAT_SEEDS
unite: 1
DisplayName: '&6Germe ensorcelée verte'
Lore: "&7&oCet objet est l'une des trois graines;&7&opermettant d'accéder au coeur de la forêt;;&eObjet de quête"

hasEnchantment: false
hideEnchantment: false

#Ingredients
Ingredient1_number_max: 5 #The maximum number of ingredients 1.
Ingredient2_number_max: 3 #The maximum number of ingredients 2.
Ingredient3_number_max: 5 #The maximum number of ingredients 3.

#The command executed when the quest is finished.
final_command: 'execute in minecraft:donjon run setblock 158 63 1276 minecraft:air'

#If it's true, nobody can do the quest. The quest is blocked.
IsBlocked: false
#If it's true, you activate the dungeon enter message.
IsMessageEnter: false

#If it's true, you activate the dungeon left message.
IsMessageLeft: false

#If it's true, a broadcast is performed on the Dungeon chat when a player ended the quest. 
IsSendBroadcastCollect: true

#If it's true, the dungeon entrance broadcast will be sent to the clicker player.
NotBroadcastPlayerFirstStart: true

#If it's true, if a player catch a ingredient, a broadcast is displayed.
MoreIngredient: true

#If it's true, if a player catch the last ingredient in a categorie, a broadcast is displayed.
IhaveAllIngredientsInCategories: true

#Ticks
start_tick: 20
finish_tick: 20